In [2]:
import pandas as pd
import numpy as np

# DataFrame Calculations

## Read DataFrame

Description: 

http://lib.stat.cmu.edu/datasets/sleep

In [7]:
# Your code here!
df_animals = pd.read_csv('http://www.statsci.org/data/general/sleep.txt', sep = '\t')
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4
...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1

species of animal

body weight in **kg**

brain weight in **g**

slow wave ("nondreaming") sleep **(hrs/day)**

paradoxical ("dreaming") sleep **(hrs/day)**

total sleep **(hrs/day)**  (sum of slow wave and paradoxical sleep)

maximum life span **(years)**

gestation time **(days)**

predation index (1-5)
                1 = minimum (least likely to be preyed upon)
                5 = maximum (most likely to be preyed upon)

sleep exposure index (1-5)
                1 = least exposed (e.g. animal sleeps in a 
                    well-protected den)
                5 = most exposed

overall danger index (1-5)
                (based on the above two indices and other information)
                1 = least danger (from other animals)
                5 = most danger (from other animals)

Note: Missing values denoted by -999.0

# DataFrame Calculations

## Performing calculations to create a new column

### Using constants

In [15]:
# criar uma coluna Ã© basicamente o mesmo processo que se faz em um dicionÃ¡rio
# dataframe['key'] = value
df_animals['new_column'] = 1

In [16]:
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1
...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1

## From lists

In [17]:
# Your code here!
df_animals['new_column_2'] = [i for i in range(len(df_animals))]
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,0
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,2
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,3
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,57
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,58
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,59
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,60
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,61

## Performing calculations of `columns` * constant

In [18]:
# Your code here!
df_animals['BrainWT_kg'] = df_animals['BrainWt']/1000
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,0,5.7120
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,0.0066
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,2,0.0445
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,3,0.0057
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,4,4.6030
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,57,0.0123
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,58,0.0025
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,59,0.0580
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,60,0.0039
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,61,0.0170

## Performing calculations within columns

In [19]:
# Your code here!
df_animals['ration_brain_body'] = df_animals.BrainWT_kg/df_animals.BodyWt
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,0,5.7120,0.000858
1,Africangiantpouchedrat,1.000,6.6,6.3,2.0,8.3,4.5,42.0,3,1,3,1,1,0.0066,0.006600
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,2,0.0445,0.013146
3,Arcticgroundsquirrel,0.920,5.7,NaN,NaN,16.5,NaN,25.0,5,2,3,1,3,0.0057,0.006196
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,4,4.6030,0.001807
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57,Treehyrax,2.000,12.3,4.9,0.5,5.4,7.5,200.0,3,1,3,1,57,0.0123,0.006150
58,Treeshrew,0.104,2.5,13.2,2.6,15.8,2.3,46.0,3,2,2,1,58,0.0025,0.024038
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,59,0.0580,0.013842
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,60,0.0039,0.001114
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,61,0.0170,0.004198

In [20]:
df_animals.ration_brain_body.describe()

count    62.000000
mean      0.009624
std       0.008915
min       0.000858
25%       0.003103
50%       0.006611
75%       0.013668
max       0.039604
Name: ration_brain_body, dtype: float64

In [21]:
df_animals[df_animals.ration_brain_body>0.03]

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body
26,Groundsquirrel,0.101,4.0,10.4,3.4,13.8,9.0,28.0,5,1,3,1,26,0.0040,0.039604
41,Owlmonkey,0.480,15.5,15.2,1.8,17.0,12.0,140.0,2,2,2,1,41,0.0155,0.032292

## Sorting results

In [22]:
# Your code here!
df_animals.sort_values(by='ration_brain_body', ascending=False, inplace=True)

In [23]:
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body
26,Groundsquirrel,0.101,4.00,10.4,3.4,13.8,9.0,28.0,5,1,3,1,26,0.00400,0.039604
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0,2,2,2,1,41,0.01550,0.032292
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,4,1,31,0.00014,0.028000
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0,2,3,2,1,49,0.17900,0.026324
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1,1,32,0.00025,0.025000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0,2,1,1,1,60,0.00390,0.001114
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0,4,5,4,1,7,0.16900,0.001056
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,4,1,44,0.18000,0.000937
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,5,1,11,0.42300,0.000910
0,Africanelephant,6654.000,5712.00,NaN,NaN,3.3,38.6,645.0,3,5,3,1,0,5.71200,0.000858

## Performing calculations row-wise

### Calculate the sum of weights for each animal

In [27]:
# Your code here!
df_animals[['BodyWt', 'BrainWT_kg']].sum(axis=1)

26       0.10500
41       0.49550
31       0.00514
49       6.97900
32       0.01025
         ...
60       3.50390
7      160.16900
44     192.18000
11     465.42300
0     6659.71200
Length: 62, dtype: float64

# Conditional Calculations

## Assign values based on conditions

In [24]:
# Your code here!
df_animals['flag_extinÃ§Ã£o'] = 0 #False
df_animals.loc[df_animals.Danger>=4, 'flag_extinÃ§Ã£o'] = 1 #True
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body,flag_extinÃ§Ã£o
26,Groundsquirrel,0.101,4.00,10.4,3.4,13.8,9.0,28.0,5,1,3,1,26,0.00400,0.039604,0
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0,2,2,2,1,41,0.01550,0.032292,0
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,4,1,31,0.00014,0.028000,1
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0,2,3,2,1,49,0.17900,0.026324,0
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1,1,32,0.00025,0.025000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0,2,1,1,1,60,0.00390,0.001114,0
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0,4,5,4,1,7,0.16900,0.001056,1
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,4,1,44,0.18000,0.000937,1
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,5,1,11,0.42300,0.000910,1
0,Africanelephant,6654.000,5712.00,NaN,NaN,3.3,38.6,645.0,3,5,3,1,0,5.71200,0.000858,0

In [29]:
df_animals.groupby(by = 'flag_extinÃ§Ã£o').mean().T

flag_extinÃ§Ã£o               0           1
BodyWt             170.050674  263.831579
BrainWt            211.964651  444.202105
NonDreaming          9.655882    6.285714
Dreaming             2.447059    0.962500
TotalSleep          11.978571    6.737500
LifeSpan            17.415385   24.931579
Gestation          103.307692  222.500000
Predation            2.139535    4.526316
Exposure             1.534884    4.421053
Danger               1.790698    4.473684
new_column           1.000000    1.000000
new_column_2        31.372093   28.526316
BrainWT_kg           0.211965    0.444202
ration_brain_body    0.011027    0.006449

# Quantiles
*Touching statistics*

> Percentiles: 
    - q50 means that 50% of your dataset is below that number. That is the median value.
    - q90 means that 90% of your dataset is below that number.
    - q10 means that 10% of your dataset is below that number.

> Calculating the q50

In [30]:
# Your code here!
df_animals.BodyWt.median()

3.3425

In [31]:
df_animals.loc[df_animals.BodyWt>df_animals.BodyWt.median(), :]

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body,flag_extinÃ§Ã£o
49,Rhesusmonkey,6.800,179.0,8.4,1.2,9.6,29.0,164.0,2,3,2,1,49,0.1790,0.026324,0
33,Man,62.000,1320.0,6.1,1.9,8.0,100.0,267.0,1,1,1,1,33,1.3200,0.021290,0
5,Baboon,10.550,179.5,9.1,0.7,9.8,27.0,180.0,4,4,4,1,5,0.1795,0.017014,1
59,Vervet,4.190,58.0,9.7,0.6,10.3,24.0,210.0,4,3,4,1,59,0.0580,0.013842,1
2,ArcticFox,3.385,44.5,NaN,NaN,12.5,14.0,60.0,1,1,1,1,2,0.0445,0.013146,0
48,Redfox,4.235,50.4,7.4,2.4,9.8,9.8,52.0,1,1,1,1,48,0.0504,0.011901,0
42,Patasmonkey,10.000,115.0,10.0,0.9,10.9,20.2,170.0,4,4,4,1,42,0.1150,0.011500,1
46,Raccoon,4.288,39.2,NaN,NaN,12.5,13.7,63.0,2,2,2,1,46,0.0392,0.009142,0
9,Chimpanzee,52.160,440.0,8.3,1.4,9.7,50.0,230.0,1,1,1,1,9,0.4400,0.008436,0
52,Roedeer,14.830,98.2,NaN,NaN,2.6,17.0,150.0,5,5,5,1,52,0.0982,0.006622,1
51,Rockhyrax(Procaviahab),3.600,21.0,4.9,0.5,5.4,6.0,225.0,3,2,3,1,51,0.0210,0.005833,0
61,Yellow-belliedmarmot,4.050,17.0,NaN,NaN,NaN,13.0,38.0,3,1,1,1,61,0.0170,0.004198,0
21,Goat,27.660,115.0,3.3,0.5,3.8,20.0,148.0,5,5,5,1,21,0.1150,0.004158,1
24,Grayseal,85.000,325.0,4.7,1.5,6.2,41.0,310.0,1,3,1,1,24,0.3250,0.003824,0
25,Graywolf,36.330,119.5,NaN,NaN,13.0,16.2,63.0,1,1,1,1,25,0.1195,0.003289,0
53,Sheep,55.500,175.0,3.2,0.6,3.8,20.0,151.0,5,5,5,1,53,0.1750,0.003153,1
39,Nine-bandedarmadillo,3.500,10.8,14.3,3.1,17.4,6.5,120.0,2,1,1,1,39,0.0108,0.003086,0
13,Donkey,187.100,419.0,NaN,NaN,3.1,40.0,365.0,5,5,5,1,13,0.4190,0.002239,1
23,Gorilla,207.000,406.0,NaN,NaN,12.0,39.3,252.0,1,4,1,1,23,0.4060,0.001961,0
40,Okapi,250.000,490.0,NaN,1.0,NaN,23.6,440.0,5,5,5,1,40,0.4900,0.001960,1
4,Asianelephant,2547.000,4603.0,2.1,1.8,3.9,69.0,624.0,3,5,4,1,4,4.6030,0.001807,1
30,Kangaroo,35.000,56.0,NaN,NaN,NaN,16.3,33.0,3,5,4,1,30,0.0560,0.001600,1
29,Jaguar,100.000,157.0,NaN,NaN,10.8,22.4,100.0,1,1,1,1,29,0.1570,0.001570,0
19,Giantarmadillo,60.000,81.0,12.0,6.1,18.1,7.0,NaN,1,1,1,1,19,0.0810,0.001350,0
20,Giraffe,529.000,680.0,NaN,0.3,NaN,28.0,400.0,5,5,5,1,20,0.6800,0.001285,1
28,Horse,521.000,655.0,2.1,0.8,2.9,46.0,336.0,5,5,5,1,28,0.6550,0.001257,1
60,Wateropossum,3.500,3.9,12.8,6.6,19.4,3.0,14.0,2,1,1,1,60,0.0039,0.001114,0
7,Braziliantapir,160.000,169.0,5.2,1.0,6.2,30.4,392.0,4,5,4,1,7,0.1690,0.001056,1
44,Pig,192.000,180.0,6.5,1.9,8.4,27.0,115.0,4,4,4,1,44,0.1800,0.000937,1
11,Cow,465.000,423.0,3.2,0.7,3.9,30.0,281.0,5,5,5,1,11,0.4230,0.000910,1
0,Africanelephant,6654.000,5712.0,NaN,NaN,3.3,38.6,645.0,3,5,3,1,0,5.7120,0.000858,0

In [34]:
df_animals.BodyWt.quantile(0.1)

0.07760000000000002

In [42]:
df_animals.BodyWt.quantile([0.1, 0.2, 0.3])

0.1    0.0776
0.2    0.3090
0.3    0.9060
Name: BodyWt, dtype: float64

## Binarizing (categorizing) data

In [43]:
# Your code here!
df_animals['BodyWt_Interval'] = pd.qcut(df_animals.BodyWt, 4, ['P', 'M', 'G', 'GG'])

In [44]:
df_animals.BodyWt_Interval.value_counts(normalize=True)

P     0.258065
GG    0.258065
M     0.241935
G     0.241935
Name: BodyWt_Interval, dtype: float64

> Calculating the threshold for different quantiles

In [46]:
# Your code here!

df_animals['BodyWt_Interval2'] = pd.cut(df_animals.BodyWt, 4)

> Selecting (and counting) the observations that are above (or below) that threshold

In [47]:
# Your code here!
q10 = df_animals.BodyWt.quantile(0.1)

In [49]:
df_animals.query(f'BodyWt < {q10}')

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body,flag_extinÃ§Ã£o,BodyWt_Interval,BodyWt_Interval2
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,4,1,31,0.00014,0.028000,1,P,"(-6.649, 1663.504]"
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1,1,32,0.00025,0.025000,0,P,"(-6.649, 1663.504]"
36,Mouse,0.023,0.40,11.9,1.3,13.2,3.2,19.0,4,1,3,1,36,0.00040,0.017391,0,P,"(-6.649, 1663.504]"
55,Starnosedmole,0.060,1.00,8.1,2.2,10.3,3.5,NaN,3,1,2,1,55,0.00100,0.016667,0,P,"(-6.649, 1663.504]"
14,EasternAmericanmole,0.075,1.20,6.3,2.1,8.4,3.5,42.0,1,1,1,1,14,0.00120,0.016000,0,P,"(-6.649, 1663.504]"
6,Bigbrownbat,0.023,0.30,15.8,3.9,19.7,19.0,35.0,1,1,1,1,6,0.00030,0.013043,0,P,"(-6.649, 1663.504]"
37,Muskshrew,0.048,0.33,10.8,2.0,12.8,2.0,30.0,4,1,3,1,37,0.00033,0.006875,0,P,"(-6.649, 1663.504]"

## Numpy where

In [50]:
import numpy as np

In [51]:
# Your code here!
q95 = df_animals.BodyWt.quantile(0.95)
np.where(df_animals.BodyWt>q95, 'SUPER OVERWEIGHT', 'NORMAL')

array(['NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL',
       'NORMAL', 'NORMAL', 'NORMAL', 'SUPER OVERWEIGHT', 'NORMAL',
       'NORMAL', 'NORMAL', 'SUPER OVERWEIGHT', 'SUPER OVERWEIGHT',
       'NORMAL', 'NORMAL', 'NORMAL', 'NORMAL', 'SUPER OVERWEIGHT'],
      dtype='<U16')

> np.where(condition is true, then this value, else this value)

In [55]:
# Your code here!
q50 = df_animals.BodyWt.quantile(0.50)
q85 = df_animals.BodyWt.quantile(0.85)
q95 = df_animals.BodyWt.quantile(0.95)
df_animals['class'] = np.where(df_animals['BodyWt'] > q95, 'SUPER-OVERWEIGHT',
                           np.where(df_animals['BodyWt'] > q85, 'ALMOST-SUPER-OVERWEIGHT', 
                                   np.where(df_animals['BodyWt'] > q50,'QUASI-ALMOST-SUPER-OVERWEIGHT','NORMAL')))

In [56]:
df_animals

,Species,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body,flag_extinÃ§Ã£o,BodyWt_Interval,BodyWt_Interval2,class
26,Groundsquirrel,0.101,4.00,10.4,3.4,13.8,9.0,28.0,5,1,3,1,26,0.00400,0.039604,0,P,"(-6.649, 1663.504]",NORMAL
41,Owlmonkey,0.480,15.50,15.2,1.8,17.0,12.0,140.0,2,2,2,1,41,0.01550,0.032292,0,P,"(-6.649, 1663.504]",NORMAL
31,Lessershort-tailedshrew,0.005,0.14,7.7,1.4,9.1,2.6,21.5,5,2,4,1,31,0.00014,0.028000,1,P,"(-6.649, 1663.504]",NORMAL
49,Rhesusmonkey,6.800,179.00,8.4,1.2,9.6,29.0,164.0,2,3,2,1,49,0.17900,0.026324,0,G,"(-6.649, 1663.504]",QUASI-ALMOST-SUPER-OVERWEIGHT
32,Littlebrownbat,0.010,0.25,17.9,2.0,19.9,24.0,50.0,1,1,1,1,32,0.00025,0.025000,0,P,"(-6.649, 1663.504]",NORMAL
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
60,Wateropossum,3.500,3.90,12.8,6.6,19.4,3.0,14.0,2,1,1,1,60,0.00390,0.001114,0,G,"(-6.649, 1663.504]",QUASI-ALMOST-SUPER-OVERWEIGHT
7,Braziliantapir,160.000,169.00,5.2,1.0,6.2,30.4,392.0,4,5,4,1,7,0.16900,0.001056,1,GG,"(-6.649, 1663.504]",ALMOST-SUPER-OVERWEIGHT
44,Pig,192.000,180.00,6.5,1.9,8.4,27.0,115.0,4,4,4,1,44,0.18000,0.000937,1,GG,"(-6.649, 1663.504]",ALMOST-SUPER-OVERWEIGHT
11,Cow,465.000,423.00,3.2,0.7,3.9,30.0,281.0,5,5,5,1,11,0.42300,0.000910,1,GG,"(-6.649, 1663.504]",ALMOST-SUPER-OVERWEIGHT
0,Africanelephant,6654.000,5712.00,NaN,NaN,3.3,38.6,645.0,3,5,3,1,0,5.71200,0.000858,0,GG,"(4990.501, 6654.0]",SUPER-OVERWEIGHT

# Bonus: 

## Correlation

*Touching statistics*

In [57]:
# Your code here!
df_animals.corr()

,BodyWt,BrainWt,NonDreaming,Dreaming,TotalSleep,LifeSpan,Gestation,Predation,Exposure,Danger,new_column,new_column_2,BrainWT_kg,ration_brain_body,flag_extinÃ§Ã£o
BodyWt,1.000000,0.934164,-0.375946,-0.109383,-0.307186,0.302451,0.651102,0.059495,0.338274,0.133581,NaN,-0.293881,0.934164,-0.206684,0.048476
BrainWt,0.934164,1.000000,-0.369218,-0.105139,-0.358102,0.509253,0.747242,0.033855,0.367800,0.145879,NaN,-0.315330,1.000000,-0.199441,0.116030
NonDreaming,-0.375946,-0.369218,1.000000,0.514254,0.962715,-0.384432,-0.594703,-0.318185,-0.543757,-0.483852,NaN,0.159300,-0.369218,0.344769,-0.422221
Dreaming,-0.109383,-0.105139,0.514254,1.000000,0.727087,-0.295745,-0.450899,-0.447471,-0.537225,-0.579337,NaN,0.006344,-0.105139,-0.056772,-0.484901
TotalSleep,-0.307186,-0.358102,0.962715,0.727087,1.000000,-0.410202,-0.631326,-0.395835,-0.642285,-0.587742,NaN,0.097175,-0.358102,0.257440,-0.512929
LifeSpan,0.302451,0.509253,-0.384432,-0.295745,-0.410202,1.000000,0.614849,-0.102544,0.360352,0.061778,NaN,-0.344098,0.509253,-0.119100,0.195450
Gestation,0.651102,0.747242,-0.594703,-0.450899,-0.631326,0.614849,1.000000,0.200504,0.638279,0.378617,NaN,-0.273520,0.747242,-0.301431,0.384384
Predation,0.059495,0.033855,-0.318185,-0.447471,-0.395835,-0.102544,0.200504,1.000000,0.618246,0.916042,NaN,0.051697,0.033855,-0.090758,0.751371
Exposure,0.338274,0.367800,-0.543757,-0.537225,-0.642285,0.360352,0.638279,0.618246,1.000000,0.787203,NaN,-0.164200,0.367800,-0.335945,0.835898
Danger,0.133581,0.145879,-0.483852,-0.579337,-0.587742,0.061778,0.378617,0.916042,0.787203,1.000000,NaN,-0.013240,0.145879,-0.216410,0.865224
new_column,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
new_column_2,-0.293881,-0.315330,0.159300,0.006344,0.097175,-0.344098,-0.273520,0.051697,-0.164200,-0.013240,NaN,1.000000,-0.315330,0.102016,-0.073312
BrainWT_kg,0.934164,1.000000,-0.369218,-0.105139,-0.358102,0.509253,0.747242,0.033855,0.367800,0.145879,NaN,-0.315330,1.000000,-0.199441,0.116030
ration_brain_body,-0.206684,-0.199441,0.344769,-0.056772,0.257440,-0.119100,-0.301431,-0.090758,-0.335945,-0.216410,NaN,0.102016,-0.199441,1.000000,-0.238691
flag_extinÃ§Ã£o,0.048476,0.116030,-0.422221,-0.484901,-0.512929,0.195450,0.384384,0.751371,0.835898,0.865224,NaN,-0.073312,0.116030,-0.238691,1.000000