# Pandas: Importing and Exporting

In [1]:
!pip install openpyxl

Defaulting to user installation because normal site-packages is not writeable
Collecting openpyxl
  Downloading openpyxl-3.0.7-py2.py3-none-any.whl (243 kB)
Collecting et-xmlfile
  Downloading et_xmlfile-1.1.0-py3-none-any.whl (4.7 kB)
Installing collected packages: et-xmlfile, openpyxl
Successfully installed et-xmlfile-1.1.0 openpyxl-3.0.7

WARNING: You are using pip version 21.0.1; however, version 21.2.1 is available.
You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.

In [3]:
!pip install xlrd

Defaulting to user installation because normal site-packages is not writeable
Collecting xlrd
  Downloading xlrd-2.0.1-py2.py3-none-any.whl (96 kB)
Installing collected packages: xlrd
Successfully installed xlrd-2.0.1

WARNING: You are using pip version 21.0.1; however, version 21.2.1 is available.
You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.

In [1]:
import xlrd
import openpyxl

In [2]:
import pandas as pd

## 1. Import **delimited files**

Most common: comma separated values `(.csv)` files. A file that is separated (or delimited) by commas (or anything else):

Examples:
    
**-- comma separated file --**

    name,year,value
    Andre,2020,100
    Fernanda,1900,1
    
**-- tab separated file --**

    name    year    value
    Andre    2020    100
    Fernanda    1900    1
    
**-- tab separated file (another way) --**

    name\tyear\tvalue
    Andre\t2020\t100
    Fernanda\t1900\t1
    
**-- hash separated file --**

    name#year#value
    Andre#2020#100
    Fernanda#1900#1

**-- pipe separated file --**

    name|year|value
    Andre|2020|100
    Fernanda|1900|1

    ...

### Comma Separated Files

In [23]:
pwd

'C:\\Users\\natmc\\GitRepository\\55_DAPT\\Classes\\Week05\\vehicles'

In [236]:
%%time
# Your code here!
pd.read_csv('vehicles/vehicles.csv', sep=',')

Wall time: 100 ms

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
35947,smart,fortwo coupe,2013,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35948,smart,fortwo coupe,2014,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,243.000000,1100
35949,smart,fortwo coupe,2015,1.0,3.0,Auto(AM5),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,38,36,244.000000,1100
35950,smart,fortwo coupe,2016,0.9,3.0,Auto(AM6),Rear-Wheel Drive,Two Seaters,Premium,9.155833,34,39,36,246.000000,1100
35951,smart,fortwo coupe,2016,0.9,3.0,Manual 5-spd,Rear-Wheel Drive,Two Seaters,Premium,9.417429,32,39,35,255.000000,1150

In this way, the `pd.read_csv()` method is just outputing the results on screen.

If I wanted to store it in a variable I would have to **assign** this result into a variable

In [35]:
# Your code here!
df = pd.read_csv('vehicles/vehicles.csv', sep=',')
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 35952 entries, 0 to 35951
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Make                     35952 non-null  object
 1   Model                    35952 non-null  object
 2   Year                     35952 non-null  int64
 3   Engine Displacement      35952 non-null  float64
 4   Cylinders                35952 non-null  float64
 5   Transmission             35952 non-null  object
 6   Drivetrain               35952 non-null  object
 7   Vehicle Class            35952 non-null  object
 8   Fuel Type                35952 non-null  object
 9   Fuel Barrels/Year        35952 non-null  float64
 10  City MPG                 35952 non-null  int64
 11  Highway MPG              35952 non-null  int64
 12  Combined MPG             35952 non-null  int64
 13  CO2 Emission Grams/Mile  35952 non-null  float64
 14  Fuel Cost/Year           35952 non-null  int64
dtypes: float64(4), int64(5), object(6)
memory usage: 4.1+ MB

### Import tab-delimited file

In [44]:
# Your code here!
pd.read_csv('vehicles/vehicles_tab.txt', sep='\t').head()

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

### Import pipe delimited file

In [235]:
%%time
# Your code here!
pd.read_csv('vehicles/vehicles_pipe.txt', sep='|').head()

Wall time: 98 ms

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6.0,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6.0,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6.0,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

## 2. Import files from URLs

Example: https://datasets.imdbws.com/

In [234]:
%%time
# Your code here!
pd.read_csv('https://datasets.imdbws.com/name.basics.tsv.gz', sep = '\t', nrows=10) #tsv: tab separeted value

KeyboardInterrupt:

In [215]:
%%time
pd.read_csv('https://datasets.imdbws.com/name.basics.tsv.gz', sep = '\t', nrows=10) #tsv: tab separeted value

Wall time: 48.9 s

,nconst,primaryName,birthYear,deathYear,primaryProfession,knownForTitles
0,nm0000001,Fred Astaire,1899,1987,"soundtrack,actor,miscellaneous","tt0053137,tt0072308,tt0031983,tt0050419"
1,nm0000002,Lauren Bacall,1924,2014,"actress,soundtrack","tt0071877,tt0117057,tt0037382,tt0038355"
2,nm0000003,Brigitte Bardot,1934,\N,"actress,soundtrack,music_department","tt0054452,tt0049189,tt0057345,tt0056404"
3,nm0000004,John Belushi,1949,1982,"actor,soundtrack,writer","tt0072562,tt0080455,tt0078723,tt0077975"
4,nm0000005,Ingmar Bergman,1918,2007,"writer,director,actor","tt0050986,tt0060827,tt0050976,tt0069467"
5,nm0000006,Ingrid Bergman,1915,1982,"actress,soundtrack,producer","tt0077711,tt0038109,tt0036855,tt0034583"
6,nm0000007,Humphrey Bogart,1899,1957,"actor,soundtrack,producer","tt0033870,tt0034583,tt0042593,tt0043265"
7,nm0000008,Marlon Brando,1924,2004,"actor,soundtrack,director","tt0047296,tt0078788,tt0070849,tt0068646"
8,nm0000009,Richard Burton,1925,1984,"actor,soundtrack,producer","tt0059749,tt0061184,tt0087803,tt0057877"
9,nm0000010,James Cagney,1899,1986,"actor,soundtrack,director","tt0035575,tt0029870,tt0031867,tt0042041"

In [216]:
%%time
df2 = pd.read_csv('https://datasets.imdbws.com/name.basics.tsv.gz', sep = '\t', nrows=100000) #tsv: tab separeted value

Wall time: 1min 31s

## 3. Import Excel Files

In [220]:
%%time
# Your code here!
pd.read_excel('vehicles/vehicles.xlsx').head()

Wall time: 9.21 s

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

## 4. Import Google Drive Files

**Cool Application: Google Sheets**

Get the shareable link and replace the last piece of the url:
* replace `/edit?usp=sharing` by `/export?format=csv`
    
(https://stackoverflow.com/questions/19611729/getting-google-spreadsheet-csv-into-a-pandas-dataframe)

In [227]:
def read_from_gsheets(spreadsheet):
    """
    Transform url into csv 
    """
    working_spreadsheet = spreadsheet.replace('/edit?usp=sharing','/export?format=csv')
    
    return pd.read_csv(working_spreadsheet)

In [230]:
# Your code here!
read_from_gsheets('https://docs.google.com/spreadsheets/d/12gg4eythcM1mctpNyCx8HJk1y3EurFfE3avOlwdGl0g/edit?usp=sharing')

   col1 col2
0     1    a
1     2    b
2     3    c
3     4    d
4     5    e

## 5. Import and export JSON files

What is a JSON file?

JSON 1:
```json
{ "name":"John", "age":30, "car":null }
```

JSON 2: 
```json
{"students":[
   {"name":"Andre", "age":23, "state":"SP"},
   {"name":"Rodrigo", "age":28, "state":"SP"},
   {"name":"Raiana", "age":32, "state":"DF"},
   {"name":"Tieko", "age":28, "state":"BA"}
]}
```

In [6]:
!ls

csv
import-export-pandas.ipynb
indexing-and-filters.ipynb
vehicles
vehicles.zip

In [10]:
%%time
# Your code here!
df = pd.read_json('vehicles/vehicles/vehicles.json')
df.head()

Wall time: 397 ms

,Make,Model,Year,Engine Displacement,Cylinders,Transmission,Drivetrain,Vehicle Class,Fuel Type,Fuel Barrels/Year,City MPG,Highway MPG,Combined MPG,CO2 Emission Grams/Mile,Fuel Cost/Year
0,AM General,DJ Po Vehicle 2WD,1984,2.5,4,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,19.388824,18,17,17,522.764706,1950
1,AM General,FJ8c Post Office,1984,4.2,6,Automatic 3-spd,2-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
2,AM General,Post Office DJ5 2WD,1985,2.5,4,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,20.600625,16,17,16,555.437500,2100
3,AM General,Post Office DJ8 2WD,1985,4.2,6,Automatic 3-spd,Rear-Wheel Drive,Special Purpose Vehicle 2WD,Regular,25.354615,13,13,13,683.615385,2550
4,ASC Incorporated,GNX,1987,3.8,6,Automatic 4-spd,Rear-Wheel Drive,Midsize Cars,Premium,20.600625,14,21,16,555.437500,2550

## Bonus: Read CSV using For
* create copy with files vehicles
* read and append

In [ ]:
# Your code here!
#lista_de_arquivos = ['file1.csv', 'file2.csv', 'file3.csv' ]
#lista_de_dataframes = [pd.read_csv(file) for file in lista_de_arquivos]
#df_final = pd.concat(lista_de_dataframes)

----

## 6. Export to `.csv`

In [11]:
# Your code here!
df.to_csv('transformed_df.csv', index=False, sep=',', decimal='.')

**NOTE**: If you do not specify the argument `index=False`, the output in the csv file will create an unnamed index column with the *dataframe indexes*.

In [12]:
# Your code here!
df.to_csv('transformed_df.csv', index=False, sep=',', decimal=',')

### Export to csv using a specific separator

In [13]:
# Semicolon
# Your code here!
df.to_csv('transformed_df.csv', index=False, sep=';', decimal=',')

In [14]:
# Pipe
# Your code here!
df.to_csv('transformed_df.csv', index=False, sep='|', decimal=',')

## 7. Export to `.xlsx`

In [17]:
# Your code here!
df.to_excel('transformed_df.xlsx', sheet_name='aba1')

-------

## 8. Export to `.json`

For a JSON file, you can have different `orient` options.

`'split'`: Dictionary containing indexes, columns, and data.

`'index'`: Nested dictionaries containing {index:{column:value}}.

`'columns'`: Nested dictionaries containing {column:{index:value}}

`'values'`: Nested list where each sublist contains the values for a record.

`'table'`: Nested dictionaries containing schema and data (records).

In [18]:
# Your code here!
df.to_json('transformed_df_split.json', orient='split')

In [19]:
df.to_json('transformed_df_index.json', orient='index')

In [20]:
df.to_json('transformed_df_columns.json', orient='columns')

----