In [1]:
!pip3 install bs4

Defaulting to user installation because normal site-packages is not writeable
Collecting bs4
  Downloading bs4-0.0.1.tar.gz (1.1 kB)
Requirement already satisfied: beautifulsoup4 in c:\users\natmc\appdata\roaming\python\python39\site-packages (from bs4) (4.10.0)
Requirement already satisfied: soupsieve>1.2 in c:\users\natmc\appdata\roaming\python\python39\site-packages (from beautifulsoup4->bs4) (2.2.1)
Using legacy 'setup.py install' for bs4, since package 'wheel' is not installed.
Installing collected packages: bs4
    Running setup.py install for bs4: started
    Running setup.py install for bs4: finished with status 'done'
Successfully installed bs4-0.0.1

WARNING: You are using pip version 21.0.1; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.

In [1]:
import pandas as pd
import numpy as np
import requests
from bs4 import BeautifulSoup

# The url to scrape

In [3]:
url = 'https://www.reuters.com/article/us-shazam-m-a-apple-eu/eu-clears-apples-purchase-of-shazam-idUSKCN1LM1TZ'

# Get the response

In [20]:
# Your code here!
response = requests.get(url)
html_str = response.text
type(response.text)

str

# Get the html

In [21]:
# Your code here!
html_bytes = response.content
type(html_bytes)

bytes

# Do the soup

In [23]:
# Your code here!
soup = BeautifulSoup(html_str)

# With the soup, you'll be able to walk through the HTML tree. 
## Looking for tag h1

In [26]:
# Your code here!
soup.find_all('h1')

It returns a list of tags.

## Looking for tag a

In [27]:
# Your code here!
soup.find_all('a')

[<a class="TextLabel__text-label___3oCVw TextLabel__gray___1V4fk TextLabel__regular___2X0ym GlobalUtility__label___35new" href="https://www.thomsonreuters.com/en/global-gateway.html">Directory of sites</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray___1V4fk TextLabel__regular___2X0ym GlobalUtility__label___35new" href="https://www.thomsonreuters.com/en/login.html">Login</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray___1V4fk TextLabel__regular___2X0ym GlobalUtility__label___35new" href="https://reuters.zendesk.com/hc/en-us/articles/216467423-Contact-Reuters">Contact</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray___1V4fk TextLabel__regular___2X0ym GlobalUtility__label___35new" href="https://reuters.zendesk.com/hc/en-us">Support</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__black-to-orange___23uc0 TextLabel__small-all-caps___2Z2RG ArticleHeader-channel-1DzNK" href="https://www.reuters.com/news/archive/USLegal">U.S. Legal News</a>,
 <a href="http://thomsonreuters.com/en/about-us/trust-principles.html">The Thomson Reuters Trust Principles.</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="//www.reuters.com/tools/mobile">Apps</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="//newslink.reuters.com/join/subscribe">Newsletters</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="//sales.reuters.com/en/ ">Advertise with Us</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="//www.reuters.com/advertising-guidelines">Advertising Guidelines</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="https://www.thomsonreuters.com/en/privacy-statement.html#cookies">Cookies</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="//www.reuters.com/terms-of-use">Terms of Use</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="https://www.thomsonreuters.com/en/privacy-statement.html">Privacy</a>,
 <a class="TextLabel__text-label___3oCVw TextLabel__gray-to-orange___3Bor1 TextLabel__regular___2X0ym" href="javascript:window.OneTrust.ToggleInfoDisplay();">Do Not Sell My Personal Information</a>,
 <a href="https://www.reuters.com/info/disclaimer" target="_blank">here for a complete list</a>,
 <a class="Footer-copyright-2ju8F" href="https://thomsonreuters.com/copyright/" role="copyright" target="_blank">© 0 Reuters. All Rights Reserved.</a>]

## Searching for a list of tags

In [30]:
# Your code here!
tags = soup.find_all(['p', 'h1', 'h2', 'h3'])

In [32]:
for tag in tags:
    print(tag.text)

Discover Thomson Reuters
EU clears Apple's purchase of Shazam
By Reuters Staff
2 Min Read
BRUSSELS (Reuters) - The European Union approved Apple’s planned acquisition of British music discovery app Shazam on Thursday, saying an EU antitrust investigation showed it would not harm competition in the bloc.
The deal, announced in December last year, would help the iPhone maker better compete with Spotify, the industry leader in music streaming services. Shazam identifies songs when a smartphone is pointed at an audio source.
“After thoroughly analyzing Shazam’s user and music data, we found that their acquisition by Apple would not reduce competition in the digital music streaming market,” EU competition commissioner Margrethe Vestager said in a statement.
“Data is key in the digital economy. We must therefore carefully review transactions which lead to the acquisition of important sets of data, including potentially commercially sensitive ones,” she added.
The European Commission opened a full-scale investigation into the deal in April, emblematic of its recent worries that companies may buy a data-rich rival to mine it for information or drive others out of the market.
Reuters last month reported sources saying that Apple was set to win unconditional EU antitrust approval for the deal following the probe requested by seven European countries including France, Italy, Spain and Sweden.
Reporting by Alissa de Carbonnel; Editing by Alastair Macdonald
Our Standards: The Thomson Reuters Trust Principles.
All quotes delayed a minimum of 15 minutes. See here for a complete list of exchanges and delays.

In [39]:
tags[0].text

'Discover Thomson Reuters'

In [35]:
tags2 = soup.find(['article'])

In [38]:
tags2.text

'By Reuters Staff2 Min ReadSlideshow ( 2 images )BRUSSELS (Reuters) - The European Union approved Apple’s planned acquisition of British music discovery app Shazam on Thursday, saying an EU antitrust investigation showed it would not harm competition in the bloc.The deal, announced in December last year, would help the iPhone maker better compete with Spotify, the industry leader in music streaming services. Shazam identifies songs when a smartphone is pointed at an audio source.“After thoroughly analyzing Shazam’s user and music data, we found that their acquisition by Apple would not reduce competition in the digital music streaming market,” EU competition commissioner Margrethe Vestager said in a statement.“Data is key in the digital economy. We must therefore carefully review transactions which lead to the acquisition of important sets of data, including potentially commercially sensitive ones,” she added.The European Commission opened a full-scale investigation into the deal in April, emblematic of its recent worries that companies may buy a data-rich rival to mine it for information or drive others out of the market.Reuters last month reported sources saying that Apple was set to win unconditional EU antitrust approval for the deal following the probe requested by seven European countries including France, Italy, Spain and Sweden.Reporting by Alissa de Carbonnel; Editing by Alastair MacdonaldOur Standards: The Thomson Reuters Trust Principles.'

In [40]:
tags3 = soup.find_all(['article'])

In [43]:
tags3.text

AttributeError: ResultSet object has no attribute 'text'. You're probably treating a list of elements like a single element. Did you call find_all() when you meant to call find()?

In [42]:
tags3[0].text

'By Reuters Staff2 Min ReadSlideshow ( 2 images )BRUSSELS (Reuters) - The European Union approved Apple’s planned acquisition of British music discovery app Shazam on Thursday, saying an EU antitrust investigation showed it would not harm competition in the bloc.The deal, announced in December last year, would help the iPhone maker better compete with Spotify, the industry leader in music streaming services. Shazam identifies songs when a smartphone is pointed at an audio source.“After thoroughly analyzing Shazam’s user and music data, we found that their acquisition by Apple would not reduce competition in the digital music streaming market,” EU competition commissioner Margrethe Vestager said in a statement.“Data is key in the digital economy. We must therefore carefully review transactions which lead to the acquisition of important sets of data, including potentially commercially sensitive ones,” she added.The European Commission opened a full-scale investigation into the deal in April, emblematic of its recent worries that companies may buy a data-rich rival to mine it for information or drive others out of the market.Reuters last month reported sources saying that Apple was set to win unconditional EU antitrust approval for the deal following the probe requested by seven European countries including France, Italy, Spain and Sweden.Reporting by Alissa de Carbonnel; Editing by Alastair MacdonaldOur Standards: The Thomson Reuters Trust Principles.'

# Another example

<ol>
    <li> request the url </li>
    <li> get its html </li>
    <li> convert to soup </li>
    <li> being a soup, we can look for tags </li>
</ol>

In [2]:
# Your code here!
url = 'https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy'

In [46]:
# Your code here!
response = requests.get(url)
html = response.text

In [48]:
soup = BeautifulSoup(html)

In [50]:
soup.find_all('p')

[<p>The map and table below cites <a href="/wiki/Life_expectancy" title="Life expectancy">life expectancy</a> per country from The World Bank's 2018 statistics.<sup class="reference" id="cite_ref-:0_1-0"><a href="#cite_note-:0-1">[1]</a></sup> Hotter colours indicate lower life expectancy, colder colours indicate high life expectancy.
 </p>]

In [51]:
soup.find_all('h1')

## Find the `table` tag whose `class=sortable wikitable`

In [70]:
# Your code here!
results = soup.find_all('table', attrs={'class': 'sortable wikitable'})
results[0].text

'\n\nRank\n\nCountry\nLife expectancy[1]\n\nInfluenza vaccination rate, people aged 65 and over, 2016 (%)[2]\n\n\n1\n\n\xa0Monaco[3]\n\n89.4\n\n\n\n\n2\n\n\xa0San Marino[4]\n\n83.4\n\n\n\n\n3\n\n\xa0\xa0Switzerland\n83.0\n\n\n\n\n4\n\n\xa0Spain\n82.8\n\n56%\n\n\n5\n\n\xa0Liechtenstein\n82.7\n\n28%\n\n\n6\n\n\xa0Italy\n82.7\n\n50%\n\n\n7\n\n\xa0Norway\n82.5\n\n38%\n\n\n8\n\n\xa0Iceland\n82.5\n\n47%\n\n\n9\n\n\xa0Luxembourg\n82.3\n\n38%\n\n\n10\n\n\xa0France\n82.3\n\n50%\n\n\n11\n\n\xa0Sweden\n82.2\n\n49%\n\n\n12\n\n\xa0Malta\n81.8\n\n\n\n\n13\n\n\xa0Finland\n81.8\n\n47%\n\n\n14\n\n\xa0Ireland\n81.6\n\n55%\n\n\n15\n\n\xa0Netherlands\n81.5\n\n65%\n\n\n16\n\n\xa0Portugal\n81.1\n\n58%\n\n\n17\n\n\xa0Greece\n81.0\n\n\n\n\n18\n\n\xa0United Kingdom\n81.0\n\n71%\n\n\n19\n\n\xa0Belgium\n81.0\n\n\n\n\n20\n\n\xa0Austria\n80.9\n\n\n\n\n21\n\n\xa0Slovenia\n80.8\n\n10%\n\n\n22\n\n\xa0Denmark\n80.7\n\n41%\n\n\n23\n\n\xa0Germany\n80.6\n\n35%\n\n\n24\n\n\xa0Cyprus\n80.5\n\n\n\n\n25\n\n\xa0Albania\n78.3\n\n\n\n\n26\n\n\xa0Czech Republic\n78.3\n\n\n\n\n27\n\n\xa0Croatia\n78.0\n\n21%\n\n\n28\n\n\xa0Estonia\n77.7\n\n3%\n\n\n29\n\n\xa0Poland\n77.5\n\n\n\n\n30\n\n\xa0Montenegro\n77.1\n\n13%\n\n\n31\n\n\xa0Bosnia and Herzegovina\n76.9\n\n\n\n\n32\n\n\xa0Slovakia\n76.6\n\n10%\n\n\n33\n\n\xa0Turkey\n75.8\n\n7%\n\n\n34\n\n\xa0North Macedonia\n75.7\n\n6%\n\n\n35\n\n\xa0Hungary\n75.6\n\n20%\n\n\n36\n\n\xa0Serbia\n75.2\n\n11%\n\n\n37\n\n\xa0Romania\n75.0\n\n8%\n\n\n38\n\n\xa0Bulgaria\n74.6\n\n\n\n\n39\n\n\xa0Latvia\n74.5\n\n4%\n\n\n40\n\n\xa0Lithuania\n74.3\n\n23%\n\n\n41\n\n\xa0Belarus\n73.8\n\n\n\n\n42\n\n\xa0Ukraine\n72.1\n\n\n\n\n43\n\n\xa0Moldova\n71.6\n\n\n\n\n44\n\n\xa0Russia\n71.6\n\n\n\n'

## get the table header `<th>`

In [89]:
# Your code here!
th_results = list()

for result in results[0].find_all('th'):
    data = result.text.strip()
    th_results.append(data)
    
th_results

['Rank',
 'Country',
 'Life expectancy[1]',
 'Influenza vaccination rate, people aged 65 and over, 2016 (%)[2]']

## get the table data `<td>`

In [86]:
# Your code here!
td_results = list()

for result in results[0].find_all('td'):
    data = result.text.strip()
    td_results.append(data)
    
td_results

['1',
 'Monaco[3]',
 '89.4',
 '',
 '2',
 'San Marino[4]',
 '83.4',
 '',
 '3',
 'Switzerland',
 '83.0',
 '',
 '4',
 'Spain',
 '82.8',
 '56%',
 '5',
 'Liechtenstein',
 '82.7',
 '28%',
 '6',
 'Italy',
 '82.7',
 '50%',
 '7',
 'Norway',
 '82.5',
 '38%',
 '8',
 'Iceland',
 '82.5',
 '47%',
 '9',
 'Luxembourg',
 '82.3',
 '38%',
 '10',
 'France',
 '82.3',
 '50%',
 '11',
 'Sweden',
 '82.2',
 '49%',
 '12',
 'Malta',
 '81.8',
 '',
 '13',
 'Finland',
 '81.8',
 '47%',
 '14',
 'Ireland',
 '81.6',
 '55%',
 '15',
 'Netherlands',
 '81.5',
 '65%',
 '16',
 'Portugal',
 '81.1',
 '58%',
 '17',
 'Greece',
 '81.0',
 '',
 '18',
 'United Kingdom',
 '81.0',
 '71%',
 '19',
 'Belgium',
 '81.0',
 '',
 '20',
 'Austria',
 '80.9',
 '',
 '21',
 'Slovenia',
 '80.8',
 '10%',
 '22',
 'Denmark',
 '80.7',
 '41%',
 '23',
 'Germany',
 '80.6',
 '35%',
 '24',
 'Cyprus',
 '80.5',
 '',
 '25',
 'Albania',
 '78.3',
 '',
 '26',
 'Czech Republic',
 '78.3',
 '',
 '27',
 'Croatia',
 '78.0',
 '21%',
 '28',
 'Estonia',
 '77.7',
 '3%',
 '29',
 'Poland',
 '77.5',
 '',
 '30',
 'Montenegro',
 '77.1',
 '13%',
 '31',
 'Bosnia and Herzegovina',
 '76.9',
 '',
 '32',
 'Slovakia',
 '76.6',
 '10%',
 '33',
 'Turkey',
 '75.8',
 '7%',
 '34',
 'North Macedonia',
 '75.7',
 '6%',
 '35',
 'Hungary',
 '75.6',
 '20%',
 '36',
 'Serbia',
 '75.2',
 '11%',
 '37',
 'Romania',
 '75.0',
 '8%',
 '38',
 'Bulgaria',
 '74.6',
 '',
 '39',
 'Latvia',
 '74.5',
 '4%',
 '40',
 'Lithuania',
 '74.3',
 '23%',
 '41',
 'Belarus',
 '73.8',
 '',
 '42',
 'Ukraine',
 '72.1',
 '',
 '43',
 'Moldova',
 '71.6',
 '',
 '44',
 'Russia',
 '71.6',
 '']

In [90]:
np.array(td_results).reshape((int(len(td_results)/4), 4))

TypeError: 'columns' is an invalid keyword argument for this function

In [91]:
pd.DataFrame(np.array(td_results).reshape((int(len(td_results)/4), 4)), columns=th_results)

,Rank,Country,Life expectancy[1],"Influenza vaccination rate, people aged 65 and over, 2016 (%)[2]"
0,1,Monaco[3],89.4,
1,2,San Marino[4],83.4,
2,3,Switzerland,83.0,
3,4,Spain,82.8,56%
4,5,Liechtenstein,82.7,28%
5,6,Italy,82.7,50%
6,7,Norway,82.5,38%
7,8,Iceland,82.5,47%
8,9,Luxembourg,82.3,38%
9,10,France,82.3,50%
10,11,Sweden,82.2,49%
11,12,Malta,81.8,
12,13,Finland,81.8,47%
13,14,Ireland,81.6,55%
14,15,Netherlands,81.5,65%
15,16,Portugal,81.1,58%
16,17,Greece,81.0,
17,18,United Kingdom,81.0,71%
18,19,Belgium,81.0,
19,20,Austria,80.9,
20,21,Slovenia,80.8,10%
21,22,Denmark,80.7,41%
22,23,Germany,80.6,35%
23,24,Cyprus,80.5,
24,25,Albania,78.3,
25,26,Czech Republic,78.3,
26,27,Croatia,78.0,21%
27,28,Estonia,77.7,3%
28,29,Poland,77.5,
29,30,Montenegro,77.1,13%
30,31,Bosnia and Herzegovina,76.9,
31,32,Slovakia,76.6,10%
32,33,Turkey,75.8,7%
33,34,North Macedonia,75.7,6%
34,35,Hungary,75.6,20%
35,36,Serbia,75.2,11%
36,37,Romania,75.0,8%
37,38,Bulgaria,74.6,
38,39,Latvia,74.5,4%
39,40,Lithuania,74.3,23%
40,41,Belarus,73.8,
41,42,Ukraine,72.1,
42,43,Moldova,71.6,
43,44,Russia,71.6,

## append results

In [ ]:
# Your code here!

## Pandas to the rescue!

In [97]:
!pip3 install lxml

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: lxml in c:\users\natmc\appdata\roaming\python\python39\site-packages (4.6.3)

WARNING: You are using pip version 21.0.1; however, version 21.2.4 is available.
You should consider upgrading via the 'c:\program files\python39\python.exe -m pip install --upgrade pip' command.

In [3]:
# Your code here!
url = "https://en.wikipedia.org/wiki/List_of_European_countries_by_life_expectancy"
r = requests.get(url)
df_list = pd.read_html(r.text)
df_list[0]

,Rank,Country,Life expectancy[1],"Influenza vaccination rate, people aged 65 and over, 2016 (%)[2]"
0,1,Monaco[3],89.4,NaN
1,2,San Marino[4],83.4,NaN
2,3,Switzerland,83.0,NaN
3,4,Spain,82.8,56%
4,5,Liechtenstein,82.7,28%
5,6,Italy,82.7,50%
6,7,Norway,82.5,38%
7,8,Iceland,82.5,47%
8,9,Luxembourg,82.3,38%
9,10,France,82.3,50%
10,11,Sweden,82.2,49%
11,12,Malta,81.8,NaN
12,13,Finland,81.8,47%
13,14,Ireland,81.6,55%
14,15,Netherlands,81.5,65%
15,16,Portugal,81.1,58%
16,17,Greece,81.0,NaN
17,18,United Kingdom,81.0,71%
18,19,Belgium,81.0,NaN
19,20,Austria,80.9,NaN
20,21,Slovenia,80.8,10%
21,22,Denmark,80.7,41%
22,23,Germany,80.6,35%
23,24,Cyprus,80.5,NaN
24,25,Albania,78.3,NaN
25,26,Czech Republic,78.3,NaN
26,27,Croatia,78.0,21%
27,28,Estonia,77.7,3%
28,29,Poland,77.5,NaN
29,30,Montenegro,77.1,13%
30,31,Bosnia and Herzegovina,76.9,NaN
31,32,Slovakia,76.6,10%
32,33,Turkey,75.8,7%
33,34,North Macedonia,75.7,6%
34,35,Hungary,75.6,20%
35,36,Serbia,75.2,11%
36,37,Romania,75.0,8%
37,38,Bulgaria,74.6,NaN
38,39,Latvia,74.5,4%
39,40,Lithuania,74.3,23%
40,41,Belarus,73.8,NaN
41,42,Ukraine,72.1,NaN
42,43,Moldova,71.6,NaN
43,44,Russia,71.6,NaN

In [4]:
pd.read_html(url)[0]

,Rank,Country,Life expectancy[1],"Influenza vaccination rate, people aged 65 and over, 2016 (%)[2]"
0,1,Monaco[3],89.4,NaN
1,2,San Marino[4],83.4,NaN
2,3,Switzerland,83.0,NaN
3,4,Spain,82.8,56%
4,5,Liechtenstein,82.7,28%
5,6,Italy,82.7,50%
6,7,Norway,82.5,38%
7,8,Iceland,82.5,47%
8,9,Luxembourg,82.3,38%
9,10,France,82.3,50%
10,11,Sweden,82.2,49%
11,12,Malta,81.8,NaN
12,13,Finland,81.8,47%
13,14,Ireland,81.6,55%
14,15,Netherlands,81.5,65%
15,16,Portugal,81.1,58%
16,17,Greece,81.0,NaN
17,18,United Kingdom,81.0,71%
18,19,Belgium,81.0,NaN
19,20,Austria,80.9,NaN
20,21,Slovenia,80.8,10%
21,22,Denmark,80.7,41%
22,23,Germany,80.6,35%
23,24,Cyprus,80.5,NaN
24,25,Albania,78.3,NaN
25,26,Czech Republic,78.3,NaN
26,27,Croatia,78.0,21%
27,28,Estonia,77.7,3%
28,29,Poland,77.5,NaN
29,30,Montenegro,77.1,13%
30,31,Bosnia and Herzegovina,76.9,NaN
31,32,Slovakia,76.6,10%
32,33,Turkey,75.8,7%
33,34,North Macedonia,75.7,6%
34,35,Hungary,75.6,20%
35,36,Serbia,75.2,11%
36,37,Romania,75.0,8%
37,38,Bulgaria,74.6,NaN
38,39,Latvia,74.5,4%
39,40,Lithuania,74.3,23%
40,41,Belarus,73.8,NaN
41,42,Ukraine,72.1,NaN
42,43,Moldova,71.6,NaN
43,44,Russia,71.6,NaN

# Creating a spider

## Find the book name, price and stock availability as a pandas dataframe.

http://books.toscrape.com/

In [6]:
# Your code here!
page = 10
url = f'http://books.toscrape.com/catalogue/page-{page}.html'
url

'http://books.toscrape.com/catalogue/page-10.html'

In [22]:
page = 1

url = f'http://books.toscrape.com/catalogue/page-{page}.html'
response = requests.get(url)
html = response.content

In [24]:
soup = BeautifulSoup(html)

In [25]:
for h3 in soup.find_all('h3'):
    for a in h3.find_all('a'):
        print(a['title'])

A Light in the Attic
Tipping the Velvet
Soumission
Sharp Objects
Sapiens: A Brief History of Humankind
The Requiem Red
The Dirty Little Secrets of Getting Your Dream Job
The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull
The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics
The Black Maria
Starving Hearts (Triangular Trade Trilogy, #1)
Shakespeare's Sonnets
Set Me Free
Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)
Rip it Up and Start Again
Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991
Olio
Mesaerion: The Best Science Fiction Stories 1800-1849
Libertarianism for Beginners
It's Only the Himalayas

In [36]:
titles_list = [a['title'] for h3 in soup.find_all('h3') for a in h3.find_all('a')]
titles_list

['A Light in the Attic',
 'Tipping the Velvet',
 'Soumission',
 'Sharp Objects',
 'Sapiens: A Brief History of Humankind',
 'The Requiem Red',
 'The Dirty Little Secrets of Getting Your Dream Job',
 'The Coming Woman: A Novel Based on the Life of the Infamous Feminist, Victoria Woodhull',
 'The Boys in the Boat: Nine Americans and Their Epic Quest for Gold at the 1936 Berlin Olympics',
 'The Black Maria',
 'Starving Hearts (Triangular Trade Trilogy, #1)',
 "Shakespeare's Sonnets",
 'Set Me Free',
 "Scott Pilgrim's Precious Little Life (Scott Pilgrim #1)",
 'Rip it Up and Start Again',
 'Our Band Could Be Your Life: Scenes from the American Indie Underground, 1981-1991',
 'Olio',
 'Mesaerion: The Best Science Fiction Stories 1800-1849',
 'Libertarianism for Beginners',
 "It's Only the Himalayas"]

In [37]:
prices_list = [float(p.text.replace('£', '')) for p in soup.find_all('p', attrs={'class' : 'price_color'})]
prices_list

[51.77,
 53.74,
 50.1,
 47.82,
 54.23,
 22.65,
 33.34,
 17.93,
 22.6,
 52.15,
 13.99,
 20.66,
 17.46,
 52.29,
 35.02,
 57.25,
 23.88,
 37.59,
 51.33,
 45.17]

In [38]:
stock_list = [p.text.strip() for p in soup.find_all('p', attrs={'class' : 'instock availability'})]
stock_list

['In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock',
 'In stock']

In [51]:
dfs = list()

for page in range (1, 51):
    
    url = f'http://books.toscrape.com/catalogue/page-{page}.html'
    
    response = requests.get(url)
    html = response.content
    soup = BeautifulSoup(html)
    
    titles_list = [a['title'] for h3 in soup.find_all('h3') for a in h3.find_all('a')]
    prices_list = [float(p.text.replace('£', '')) for p in soup.find_all('p', attrs={'class' : 'price_color'})]
    stock_list = [p.text.strip() for p in soup.find_all('p', attrs={'class' : 'instock availability'})]

    dfs.append(pd.DataFrame({'title':titles_list, 'price':prices_list, 'stock':stock_list, 'page':page}))

In [52]:
df = pd.concat(dfs, ignore_index=True)
df

                                                 title  price     stock  page
0                                 A Light in the Attic  51.77  In stock     1
1                                   Tipping the Velvet  53.74  In stock     1
2                                           Soumission  50.10  In stock     1
3                                        Sharp Objects  47.82  In stock     1
4                Sapiens: A Brief History of Humankind  54.23  In stock     1
..                                                 ...    ...       ...   ...
995  Alice in Wonderland (Alice's Adventures in Won...  55.53  In stock    50
996   Ajin: Demi-Human, Volume 1 (Ajin: Demi-Human #1)  57.06  In stock    50
997  A Spy's Devotion (The Regency Spies of London #1)  16.97  In stock    50
998                1st to Die (Women's Murder Club #1)  53.98  In stock    50
999                 1,000 Places to See Before You Die  26.08  In stock    50

[1000 rows x 4 columns]

In [53]:
df.price.describe()

count    1000.00000
mean       35.07035
std        14.44669
min        10.00000
25%        22.10750
50%        35.98000
75%        47.45750
max        59.99000
Name: price, dtype: float64

In [55]:
df.stock.value_counts()

In stock    1000
Name: stock, dtype: int64